apiVersion : apps/v1
kind: Deployment
metadata:
  name: sitereposk8s 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sitereposk8s
  template:
    metadata:
      labels:
        app: sitereposk8s
    spec:
      containers:
        - name: sitereposk8s
          image: IMAGE-DEPLOYMENT
          ports:
          - containerPort: 80
